spring:
  application:
    name: chatapp-backend
    
  # --- PostgreSQL Settings  ---
  datasource:
    url: jdbc:postgresql://localhost:8082/pingpongchatdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
        
# --- H2 Settings (Commented) ---
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false
        
# --- Common  ---
  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
